import Head from "next/head";
import { Fragment } from "react/cjs/react.production.min";
import Featured from "../components/Featured";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <title>Food Ordering</title>
      </Head>
      <Featured />
    </Fragment>
  );
}
